In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
df_sample = pd.read_csv("/Users/shamilikolli/Downloads/videoStatististicsALL_from21_anonymized.csv",sep=";", nrows=1000   )

In [8]:
df_sample.head()

   Unnamed: 0  video_id           created_at  comments  dislikes  likes  views
0           0    100000  2021-05-31T20:00:14       1.0       0.0   16.0    162
1           1    100000  2021-05-31T21:00:14      14.0       2.0   36.0    266
2           2    100000  2021-05-31T22:00:12      17.0       2.0   49.0   1474
3           3    100000  2021-05-31T23:00:12      18.0       3.0   56.0   3746
4           4    100000  2021-06-01T00:00:12      18.0       3.0   62.0   5625

In [17]:
df_test = df_sample[df_sample["video_id"] == 100001]

In [10]:
df_test.shape

(170, 7)

In [19]:
df_test.head(40)

,Unnamed: 0,video_id,created_at,comments,dislikes,likes,views
170,170,100001,2021-05-31T17:00:13,3.0,2.0,30.0,310
171,171,100001,2021-05-31T18:00:14,14.0,9.0,78.0,870
172,172,100001,2021-05-31T19:00:15,47.0,10.0,113.0,1230
173,173,100001,2021-05-31T20:00:14,72.0,11.0,150.0,5448
174,174,100001,2021-05-31T21:00:14,87.0,14.0,180.0,9335
175,175,100001,2021-05-31T22:00:12,95.0,15.0,201.0,13145
176,176,100001,2021-05-31T23:00:12,104.0,16.0,212.0,15347
177,177,100001,2021-06-01T00:00:12,112.0,16.0,219.0,17888
178,178,100001,2021-06-01T01:00:14,116.0,17.0,222.0,19429
179,179,100001,2021-06-01T02:00:14,116.0,18.0,227.0,20409
180,180,100001,2021-06-01T03:00:11,120.0,18.0,228.0,20899
181,181,100001,2021-06-01T04:00:13,122.0,19.0,230.0,21333
182,182,100001,2021-06-01T05:00:10,122.0,19.0,231.0,21662
183,183,100001,2021-06-01T06:00:12,122.0,19.0,232.0,21827
184,184,100001,2021-06-01T07:00:11,122.0,19.0,231.0,21954
185,185,100001,2021-06-01T08:00:13,122.0,20.0,231.0,22084
186,186,100001,2021-06-01T09:00:12,124.0,20.0,232.0,22240
187,187,100001,2021-06-01T10:00:13,125.0,20.0,232.0,22413
188,188,100001,2021-06-01T11:00:12,127.0,20.0,234.0,22687
189,189,100001,2021-06-01T12:00:12,127.0,20.0,235.0,22979
190,190,100001,2021-06-01T13:00:14,127.0,20.0,234.0,23186
191,191,100001,2021-06-01T14:00:14,127.0,20.0,236.0,23405
192,192,100001,2021-06-01T15:00:14,127.0,21.0,239.0,23634
193,193,100001,2021-06-01T16:00:12,128.0,21.0,239.0,23692
194,194,100001,2021-06-01T17:00:16,128.0,22.0,239.0,23949
195,195,100001,2021-06-01T18:00:12,132.0,22.0,242.0,24200
196,196,100001,2021-06-01T19:00:15,130.0,22.0,243.0,24420
197,197,100001,2021-06-01T20:00:13,131.0,22.0,245.0,24649
198,198,100001,2021-06-01T21:00:11,132.0,22.0,248.0,24848
199,199,100001,2021-06-01T22:00:15,132.0,22.0,249.0,25054
200,200,100001,2021-06-01T23:00:10,132.0,22.0,249.0,25238
201,201,100001,2021-06-02T00:00:12,136.0,22.0,250.0,25462
202,202,100001,2021-06-02T01:00:11,136.0,22.0,250.0,25749
203,203,100001,2021-06-02T02:00:14,136.0,22.0,250.0,26007
204,204,100001,2021-06-02T03:00:12,136.0,22.0,251.0,26307
205,205,100001,2021-06-02T04:00:10,137.0,22.0,251.0,26506
206,206,100001,2021-06-02T05:00:11,137.0,23.0,251.0,26655
207,207,100001,2021-06-02T06:00:11,137.0,23.0,251.0,26762
208,208,100001,2021-06-02T07:00:11,137.0,23.0,251.0,26841
209,209,100001,2021-06-02T08:00:12,137.0,23.0,251.0,26887

In [14]:
df_sample[190]

KeyError: 190

In [16]:

print(df_sample['video_id'].unique())

[100000 100001 100002 100003 100004 100005]